## Import libraries

In [1]:
import pandas as pd
import numpy as np
import category_encoders as ce

C:\Users\lcruz\Anaconda3\lib\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.8' currently installed).
  warnings.warn(msg, UserWarning)

## Import Dataset

In [76]:
data = pd.read_csv('Yelp Dataset Shortened.csv')
data

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,state,postal_code,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,PA,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,PA,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,PA,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,PA,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,PA,19114,40.079848,-75.025080,4.0,181,1,"{'Caters': 'True', 'Ambience': ""{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,MO,63043,38.713891,-90.449468,2.5,35,1,"{'OutdoorSeating': 'False', 'RestaurantsTakeOu...","Food, Restaurants, Bakeries, Indian","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,FL,33617,28.053329,-82.392815,3.0,172,1,"{'OutdoorSeating': 'True', 'BusinessAcceptsCre...","Sports Bars, Breakfast & Brunch, Mexican, Nigh...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ..."
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,LA,70115,29.920869,-90.099728,4.0,41,0,"{'Caters': 'False', 'BikeParking': 'True', 'Wi...","Cafes, Bakeries, Restaurants, Food","{'Tuesday': '7:0-17:0', 'Wednesday': '7:0-17:0..."
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,NJ,08518,40.101977,-74.796668,3.0,58,0,"{'BikeParking': 'False', 'WiFi': ""u'free'"", 'B...","Irish Pub, American (New), Restaurants, Nightl...","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ..."
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,IN,46038,39.959788,-86.038480,4.5,7,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Pizza, Restaurants","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'..."

## Categories Column EDA

From my EDA, I see that there are 194 unique categories. 194 categories is way too many categories to include in an analysis, so I also did a breakdown of how many times each categories appears in the dataset. I want to only use the most popular/relevant

In [3]:
categories = []

stop_words = ['Food', 'Restaurants'] #filter out these words because they are redundant
for cat in data['categories']:
    cat_split = cat.split()
    nums_removed = [i for i in cat_split if i.isalpha()] # remove numbers and puncuation 
    stop_removed = [i for i in nums_removed if i not in stop_words] # remove the stop words
    for i in stop_removed:
        categories.append(i)
        
categories_unique = set(categories) # all the unique categories in the column
    
categories_unique

{'Acai',
 'Active',
 'Adult',
 'American',
 'Amusement',
 'Argentine',
 'Art',
 'Arts',
 'Asian',
 'Bagels',
 'Bakeries',
 'Banks',
 'Bar',
 'Barbeque',
 'Bars',
 'Batting',
 'Beauty',
 'Bed',
 'Beer',
 'Bowls',
 'Breakfast',
 'Breweries',
 'Brunch',
 'Bubble',
 'Buffets',
 'Burgers',
 'Cafes',
 'Cambodian',
 'Canadian',
 'Candy',
 'Caribbean',
 'Caterers',
 'Centers',
 'Cheesesteaks',
 'Chicken',
 'Chinese',
 'Chips',
 'Chocolatiers',
 'Cocktail',
 'Coffee',
 'Comfort',
 'Community',
 'Computer',
 'Convenience',
 'Cooking',
 'Court',
 'Crafts',
 'Cream',
 'Credit',
 'Creperies',
 'Cuban',
 'Cuisine',
 'Dance',
 'Day',
 'Delicatessen',
 'Delis',
 'Delivery',
 'Desserts',
 'Dim',
 'Diners',
 'Dive',
 'Dog',
 'Dogs',
 'Donuts',
 'Eastern',
 'Entertainment',
 'Ethiopian',
 'Ethnic',
 'Event',
 'Farmers',
 'Fast',
 'Financial',
 'Fish',
 'Fitness',
 'Flavor',
 'Flowers',
 'French',
 'Frozen',
 'Fruits',
 'Fusion',
 'Gas',
 'Gastropubs',
 'Gay',
 'German',
 'Golf',
 'Greek',
 'Grocery',
 'Hair',
 'Hawaiian',
 'Health',
 'Herbs',
 'Home',
 'Hookah',
 'Hot',
 'Hotels',
 'IT',
 'Ice',
 'Imported',
 'Indian',
 'Internet',
 'Irish',
 'Italian',
 'Japanese',
 'Jazz',
 'Juice',
 'Kids',
 'Kitchen',
 'Korean',
 'Laotian',
 'Latin',
 'Lebanese',
 'Life',
 'Local',
 'Lounges',
 'Markets',
 'Meat',
 'Mediterranean',
 'Mexican',
 'Middle',
 'Mini',
 'Modern',
 'Mongolian',
 'Music',
 'New',
 'Nightlife',
 'Noodles',
 'Organic',
 'Outdoor',
 'Pakistani',
 'Pan',
 'Parks',
 'Party',
 'Pasta',
 'Performing',
 'Personal',
 'Pet',
 'Photography',
 'Piano',
 'Pizza',
 'Planning',
 'Plates',
 'Pool',
 'Pot',
 'Pubs',
 'Puerto',
 'Ramen',
 'Real',
 'Resorts',
 'Rican',
 'Salad',
 'Salons',
 'Salvadoran',
 'Sandwiches',
 'Seafood',
 'Services',
 'Shop',
 'Shopping',
 'Shops',
 'Skin',
 'Smoothies',
 'Soul',
 'Soup',
 'Southern',
 'Souvenir',
 'Spaces',
 'Spanish',
 'Spas',
 'Specialty',
 'Spirits',
 'Sporting',
 'Sports',
 'Steakhouses',
 'Stores',
 'Street',
 'Sum',
 'Sushi',
 'Szechuan',
 'Tacos',
 'Tapas',
 'Tea',
 'Teppanyaki',
 'Thai',
 'Tiki',
 'Travel',
 'Turkish',
 'Vegan',
 'Vegetarian',
 'Veggies',
 'Venues',
 'Vietnamese',
 'Whiskey',
 'Wine',
 'Wings',
 'Yogurt'}

In [4]:
len(categories_unique)

194

In [5]:
import numpy as np
cat_pop = pd.value_counts(np.array(categories))
cat_pop[0:51]

American         1994
Breakfast        1013
Coffee            511
Event             418
Cocktail          385
Bars              380
Planning          329
Brunch            303
Nightlife         294
Wine              278
Sushi             273
Fast              208
Specialty         196
Arts              168
Chicken           166
Asian             166
Sports            160
Beer              142
Sandwiches        133
Italian           132
Juice             124
Seafood           124
Pizza             121
Comfort           119
Mexican           112
Hotels            106
Latin             102
Music              99
Venues             90
Japanese           89
Frozen             81
Cream              81
Ice                81
Bakeries           79
Burgers            74
Services           63
Thai               58
Salad              55
Hot                52
Local              48
Tea                47
Pubs               46
Soul               41
Middle             39
Delivery           39
Vegetarian         39
Dive               37
Entertainment      36
Chinese            36
Soup               36
Southern           36
dtype: int64

In [77]:
import ast
attributes = []

for att in data['attributes']:
    attributes_dict = ast.literal_eval(att)
    keys = list(attributes_dict.keys())
    for i in keys:
        attributes.append(i)

set(attributes)

{'Alcohol',
 'Ambience',
 'BYOB',
 'BYOBCorkage',
 'BestNights',
 'BikeParking',
 'BusinessAcceptsBitcoin',
 'BusinessAcceptsCreditCards',
 'BusinessParking',
 'ByAppointmentOnly',
 'Caters',
 'CoatCheck',
 'Corkage',
 'DietaryRestrictions',
 'DogsAllowed',
 'DriveThru',
 'GoodForDancing',
 'GoodForKids',
 'GoodForMeal',
 'HappyHour',
 'HasTV',
 'Music',
 'NoiseLevel',
 'Open24Hours',
 'OutdoorSeating',
 'RestaurantsAttire',
 'RestaurantsDelivery',
 'RestaurantsGoodForGroups',
 'RestaurantsPriceRange2',
 'RestaurantsReservations',
 'RestaurantsTableService',
 'RestaurantsTakeOut',
 'Smoking',
 'WheelchairAccessible',
 'WiFi'}

In [78]:
attr

101242

In [37]:
att_pop = pd.value_counts(np.array(attributes))
att_pop

RestaurantsPriceRange2        4676
RestaurantsTakeOut            4651
RestaurantsDelivery           4648
BusinessParking               4642
BusinessAcceptsCreditCards    4631
OutdoorSeating                4606
GoodForKids                   4591
RestaurantsReservations       4584
RestaurantsGoodForGroups      4579
Ambience                      4574
HasTV                         4562
Alcohol                       4545
RestaurantsAttire             4544
WiFi                          4527
NoiseLevel                    4522
BikeParking                   4455
Caters                        4431
GoodForMeal                   4040
RestaurantsTableService       2842
HappyHour                     2546
DogsAllowed                   2360
WheelchairAccessible          2006
BusinessAcceptsBitcoin        1264
Music                         1120
BestNights                    1054
ByAppointmentOnly              972
CoatCheck                      934
GoodForDancing                 921
Smoking                        815
BYOB                           787
DriveThru                      704
Corkage                        668
BYOBCorkage                    428
Open24Hours                     10
DietaryRestrictions              3
dtype: int64

## Attributes to Columns in Our Dataset

In [38]:
interested_attributes = ['RestaurantsPriceRange2', 'RestaurantsTakeOut', 'RestaurantsDelivery', 'BusinessParking', 'Ambience', 'WiFi']
RestaurantsPriceRange2 = []
RestaurantsTakeOut = []
RestaurantsDelivery = [] 
BusinessParking = []
Ambience = []
WiFi = []

for att in data['attributes']:
    attributes_dict = ast.literal_eval(att)
    keys = list(attributes_dict.keys())
    for ia in interested_attributes:
        if ia in keys:
            globals()[ia].append(attributes_dict[ia])
        else:
            globals()[ia].append(np.nan)

In [39]:
Ambience_wo_na = []
amb_att = []

for att in data['attributes']:
    attributes_dict = ast.literal_eval(att)
    keys = list(attributes_dict.keys())
    if 'Ambience' in keys:
        Ambience_wo_na.append(attributes_dict['Ambience'])

for att in Ambience_wo_na:
    attributes_dict = ast.literal_eval(att)
    if attributes_dict != None:
        keys = list(attributes_dict.keys())
        for i in keys:
            amb_att.append(i)

set(amb_att)

{'casual',
 'classy',
 'divey',
 'hipster',
 'intimate',
 'romantic',
 'touristy',
 'trendy',
 'upscale'}

In [40]:
interested_attributes = ['hipster', 'touristy', 'trendy', 'upscale']
hipster = []
touristy = []
trendy = []
upscale = []

for att in Ambience:
    if pd.isna(att) or (att == 'None'):
        for ia in interested_attributes:
            globals()[ia].append(np.nan)
    else:
        attributes_dict = ast.literal_eval(att)
        keys = list(attributes_dict.keys())
        for ia in interested_attributes:
            if ia in keys:
                globals()[ia].append(attributes_dict[ia])
            else:
                globals()[ia].append(np.nan)

In [41]:
interested_attributes = ['garage', 'street', 'lot', 'validated', 'valet']
garage = []
street = []
lot = []
validated = []
valet =  []

for att in BusinessParking:
    if pd.isna(att) or (att == 'None'):
        for ia in interested_attributes:
            globals()[ia].append(np.nan)
    else:
        attributes_dict = ast.literal_eval(att)
        keys = list(attributes_dict.keys())
        for ia in interested_attributes:
            if ia in keys:
                globals()[ia].append(attributes_dict[ia])
            else:
                globals()[ia].append(np.nan)

## Adding columns to dataset

In [42]:
data['RestaurantsPriceRange'] = RestaurantsPriceRange2
data

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,postal_code,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours,RestaurantsPriceRange
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,19114,40.079848,-75.025080,4.0,181,1,"{'Caters': 'True', 'Ambience': ""{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21...",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,63043,38.713891,-90.449468,2.5,35,1,"{'OutdoorSeating': 'False', 'RestaurantsTakeOu...","Food, Restaurants, Bakeries, Indian","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",2
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,33617,28.053329,-82.392815,3.0,172,1,"{'OutdoorSeating': 'True', 'BusinessAcceptsCre...","Sports Bars, Breakfast & Brunch, Mexican, Nigh...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ...",1
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,70115,29.920869,-90.099728,4.0,41,0,"{'Caters': 'False', 'BikeParking': 'True', 'Wi...","Cafes, Bakeries, Restaurants, Food","{'Tuesday': '7:0-17:0', 'Wednesday': '7:0-17:0...",1
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,08518,40.101977,-74.796668,3.0,58,0,"{'BikeParking': 'False', 'WiFi': ""u'free'"", 'B...","Irish Pub, American (New), Restaurants, Nightl...","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ...",2
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,46038,39.959788,-86.038480,4.5,7,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Pizza, Restaurants","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'...",1

In [43]:
data['RestaurantsTakeOut'] = RestaurantsTakeOut
data

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours,RestaurantsPriceRange,RestaurantsTakeOut
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,40.079848,-75.025080,4.0,181,1,"{'Caters': 'True', 'Ambience': ""{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21...",2,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,38.713891,-90.449468,2.5,35,1,"{'OutdoorSeating': 'False', 'RestaurantsTakeOu...","Food, Restaurants, Bakeries, Indian","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",2,True
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,28.053329,-82.392815,3.0,172,1,"{'OutdoorSeating': 'True', 'BusinessAcceptsCre...","Sports Bars, Breakfast & Brunch, Mexican, Nigh...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ...",1,True
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,29.920869,-90.099728,4.0,41,0,"{'Caters': 'False', 'BikeParking': 'True', 'Wi...","Cafes, Bakeries, Restaurants, Food","{'Tuesday': '7:0-17:0', 'Wednesday': '7:0-17:0...",1,True
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,40.101977,-74.796668,3.0,58,0,"{'BikeParking': 'False', 'WiFi': ""u'free'"", 'B...","Irish Pub, American (New), Restaurants, Nightl...","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ...",2,True
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,39.959788,-86.038480,4.5,7,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Pizza, Restaurants","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'...",1,True

In [44]:
data['RestaurantsDelivery'] = RestaurantsDelivery
data

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,longitude,stars_y,review_count,is_open,attributes,categories,hours,RestaurantsPriceRange,RestaurantsTakeOut,RestaurantsDelivery
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,-75.223639,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,-75.025080,4.0,181,1,"{'Caters': 'True', 'Ambience': ""{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21...",2,True,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,-90.449468,2.5,35,1,"{'OutdoorSeating': 'False', 'RestaurantsTakeOu...","Food, Restaurants, Bakeries, Indian","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",2,True,True
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,-82.392815,3.0,172,1,"{'OutdoorSeating': 'True', 'BusinessAcceptsCre...","Sports Bars, Breakfast & Brunch, Mexican, Nigh...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ...",1,True,True
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,-90.099728,4.0,41,0,"{'Caters': 'False', 'BikeParking': 'True', 'Wi...","Cafes, Bakeries, Restaurants, Food","{'Tuesday': '7:0-17:0', 'Wednesday': '7:0-17:0...",1,True,False
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,-74.796668,3.0,58,0,"{'BikeParking': 'False', 'WiFi': ""u'free'"", 'B...","Irish Pub, American (New), Restaurants, Nightl...","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ...",2,True,False
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,-86.038480,4.5,7,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Pizza, Restaurants","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'...",1,True,True

In [45]:
data['WiFi'] = WiFi
data

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,stars_y,review_count,is_open,attributes,categories,hours,RestaurantsPriceRange,RestaurantsTakeOut,RestaurantsDelivery,WiFi
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free'
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free'
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free'
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,3.0,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free'
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,4.0,181,1,"{'Caters': 'True', 'Ambience': ""{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21...",2,True,None,u'no'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,2.5,35,1,"{'OutdoorSeating': 'False', 'RestaurantsTakeOu...","Food, Restaurants, Bakeries, Indian","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",2,True,True,'no'
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,3.0,172,1,"{'OutdoorSeating': 'True', 'BusinessAcceptsCre...","Sports Bars, Breakfast & Brunch, Mexican, Nigh...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ...",1,True,True,u'free'
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,4.0,41,0,"{'Caters': 'False', 'BikeParking': 'True', 'Wi...","Cafes, Bakeries, Restaurants, Food","{'Tuesday': '7:0-17:0', 'Wednesday': '7:0-17:0...",1,True,False,u'free'
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,3.0,58,0,"{'BikeParking': 'False', 'WiFi': ""u'free'"", 'B...","Irish Pub, American (New), Restaurants, Nightl...","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ...",2,True,False,u'free'
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,4.5,7,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Pizza, Restaurants","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'...",1,True,True,NaN

In [46]:
data['Trendy'] = trendy
data

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,review_count,is_open,attributes,categories,hours,RestaurantsPriceRange,RestaurantsTakeOut,RestaurantsDelivery,WiFi,Trendy
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free',False
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free',False
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free',False
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,169,1,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free',False
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,181,1,"{'Caters': 'True', 'Ambience': ""{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21...",2,True,None,u'no',False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,35,1,"{'OutdoorSeating': 'False', 'RestaurantsTakeOu...","Food, Restaurants, Bakeries, Indian","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",2,True,True,'no',False
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,172,1,"{'OutdoorSeating': 'True', 'BusinessAcceptsCre...","Sports Bars, Breakfast & Brunch, Mexican, Nigh...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ...",1,True,True,u'free',None
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,41,0,"{'Caters': 'False', 'BikeParking': 'True', 'Wi...","Cafes, Bakeries, Restaurants, Food","{'Tuesday': '7:0-17:0', 'Wednesday': '7:0-17:0...",1,True,False,u'free',False
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,58,0,"{'BikeParking': 'False', 'WiFi': ""u'free'"", 'B...","Irish Pub, American (New), Restaurants, Nightl...","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ...",2,True,False,u'free',False
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,7,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Pizza, Restaurants","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'...",1,True,True,NaN,False

In [47]:
data['Hipster'] = hipster
data['Upscale'] = upscale
data['Touristy'] = touristy
data

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,categories,hours,RestaurantsPriceRange,RestaurantsTakeOut,RestaurantsDelivery,WiFi,Trendy,Hipster,Upscale,Touristy
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,"Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free',False,False,False,False
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,"Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free',False,False,False,False
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,"Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free',False,False,False,False
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,"Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...",2,True,True,'free',False,False,False,False
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,"Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21...",2,True,None,u'no',False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,"Food, Restaurants, Bakeries, Indian","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",2,True,True,'no',False,False,False,False
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,"Sports Bars, Breakfast & Brunch, Mexican, Nigh...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ...",1,True,True,u'free',None,None,False,None
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,"Cafes, Bakeries, Restaurants, Food","{'Tuesday': '7:0-17:0', 'Wednesday': '7:0-17:0...",1,True,False,u'free',False,False,False,False
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,"Irish Pub, American (New), Restaurants, Nightl...","{'Monday': '11:0-0:0', 'Tuesday': '11:0-0:0', ...",2,True,False,u'free',False,False,False,False
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,"Pizza, Restaurants","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'...",1,True,True,NaN,False,False,False,False

In [48]:
data['Garage'] = garage
data['Street'] = street
data['Lot'] = lot
data['Validated'] = validated
data['Valet'] = valet
data

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,WiFi,Trendy,Hipster,Upscale,Touristy,Garage,Street,Lot,Validated,Valet
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,'free',False,False,False,False,False,False,True,False,False
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,'free',False,False,False,False,False,False,True,False,False
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,'free',False,False,False,False,False,False,True,False,False
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,'free',False,False,False,False,False,False,True,False,False
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,u'no',False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,'no',False,False,False,False,None,None,True,None,False
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,u'free',None,None,False,None,False,False,True,False,False
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,u'free',False,False,False,False,False,True,False,False,False
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,u'free',False,False,False,False,False,False,True,False,False
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,NaN,False,False,False,False,False,False,False,False,False

## Combine parking columns to reduce the number of columns in the dataset

In [49]:
def free_parking(row):
    # if there's lot parking, then free
    # if there's valet parking that's validated, then free
    # if there's street and garage parking that's validated, then free
    # else not free
    if (row['Lot'] == True) or ((row['Valet'] == True) and (row['Validated'] == True)) or ((row['Street'] == True) and (row['Validated'] == True)) or ((row['Garage'] == True) and (row['Validated'] == True)):
        parking = 1
    else:
        parking = 0
        
    return parking

In [50]:
fp = []
for i in range(4696):
    fp.append(free_parking(data.iloc[i,:]))

In [51]:
data['Free Parking'] = fp
data

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,Trendy,Hipster,Upscale,Touristy,Garage,Street,Lot,Validated,Valet,Free Parking
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,False,False,False,False,False,False,True,False,False,1
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,False,False,False,False,False,False,True,False,False,1
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,False,False,False,False,False,False,True,False,False,1
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,False,False,False,False,False,False,True,False,False,1
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,False,False,False,False,False,False,True,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,False,False,False,False,None,None,True,None,False,1
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,None,None,False,None,False,False,True,False,False,1
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,False,False,False,False,False,True,False,False,False,0
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,False,False,False,False,False,False,True,False,False,1
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,False,False,False,False,False,False,False,False,False,0

## Encode da variables

In [69]:
def encode_prices(x):
    if x == '1':
        return 0
    if x ==  '2':
        return 1
    if x ==  '3':
        return 2
    if x ==  '4':
        return 3
    if pd.isna(x):
        return 0

def encode(x):
    if (x == False) or (x == None) or (x == 'False') or (x == 'None'):
        return 0
    if pd.isna(x):
        return 0
    if (x == True) or (x == 'True'):
        return 1
    
def encode_wifi(x):
    if (x == "'free'") or (x == "u'free'"):
        return 1
    else:
        return 0

def encode_states(x): # regions defined by census    
    if (x == 'AZ') or (x == 'CA') or (x == 'NV'): # west
        return 0 
    if (x == 'AB') or (x == 'DE') or (x == 'FL') or (x == 'LA') or (x == 'TN'): # south
        return 1
    if (x == 'ID') or (x == 'IL') or (x == 'IN') or (x == 'MO'): #midwest
        return 2
    if (x == 'NJ') or (x == 'PA'): # east
        return 3

In [56]:
data_encoded = data.copy()
data_encoded['RestaurantsPriceRange'] = data_encoded['RestaurantsPriceRange'].apply(encode_prices)

In [57]:
data_encoded['RestaurantsDelivery'] = data_encoded['RestaurantsDelivery'].apply(encode)
data_encoded['RestaurantsTakeOut'] = data_encoded['RestaurantsTakeOut'].apply(encode)
data_encoded['Hipster'] = data_encoded['Hipster'].apply(encode)
data_encoded['Touristy'] = data_encoded['Touristy'].apply(encode)
data_encoded['Trendy'] = data_encoded['Trendy'].apply(encode)
data_encoded['Upscale'] = data_encoded['Upscale'].apply(encode)
data_encoded['WiFi'] = data_encoded['WiFi'].apply(encode_wifi)

In [70]:
data_encoded['Regions'] = data_encoded['state'].apply(encode_states)

In [71]:
data_encoded

,Unnamed: 0,index,Unnamed: 0.1,review_id,user_id,business_id,stars_x,useful,funny,cool,...,Hipster,Upscale,Touristy,Garage,Street,Lot,Validated,Valet,Free Parking,Regions
0,0,0,0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,0,0,0,False,False,True,False,False,1,3
1,1,1,1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,0,0,0,...,0,0,0,False,False,True,False,False,1,3
2,2,2,2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,2,0,1,...,0,0,0,False,False,True,False,False,1,3
3,3,3,3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,...,0,0,0,False,False,True,False,False,1,3
4,4,4,4,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,...,0,0,0,False,False,True,False,False,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,4844,6758,6758,M1ge08vZxr3FtGbkv_0hdA,yTT_1lLxSi3xSkABU-IcLw,iHC-f9m5EEOIJMXCW3bmBA,4.0,0,0,1,...,0,0,0,None,None,True,None,False,1,2
4692,4845,6760,6760,f5L0GswmYnHZ30bNCtyEMQ,B_NlUelnLqCuxV4NaZJxDw,_HcAoG6Jj_XTj4-XNEbo6Q,3.0,0,0,0,...,0,0,0,False,False,True,False,False,1,1
4693,4846,6765,6765,vZ4BXyD-omH9cacOD7i8pg,9Hn00AuZlNCxGYoGUdnHBQ,K4TlU26IH19tM_VvTMnpyg,5.0,5,1,2,...,0,0,0,False,True,False,False,False,0,1
4694,4847,6766,6766,R_w4zUc5-dPIgCreDBL5PA,w9_aZDRgSTmokiPh0yPDEg,PXsDX1wvizL93PcMAgxQ7w,4.0,1,1,0,...,0,0,0,False,False,True,False,False,1,3
4695,4848,6767,6767,_b2Yvq8LZ9sdNAEjS7jgEw,k9Mvnw4aglONCaS5cBKQnw,yqBU6jO9e988dwxBkstJFQ,5.0,2,0,0,...,0,0,0,False,False,False,False,False,0,2

In [72]:
final_df = data_encoded.drop(columns = ['Unnamed: 0', 'Unnamed: 0.1', 'user_id', 'stars_x', 'funny', 'cool', 'review_count', 'attributes', 'categories', 'hours', 'Garage', 'Street', 'Lot', 'Validated', 'Valet'])
final_df

,index,review_id,business_id,useful,text,date,name,address,city,state,...,RestaurantsPriceRange,RestaurantsTakeOut,RestaurantsDelivery,WiFi,Trendy,Hipster,Upscale,Touristy,Free Parking,Regions
0,0,KU_O5udG6zpxOg-VcAEodg,XQfwVwDr-v0ZS3_CbbE5Xw,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,...,1,1,1,1,0,0,0,0,1,3
1,1,VJxlBnJmCDIy8DFG0kjSow,XQfwVwDr-v0ZS3_CbbE5Xw,0,This is the second time we tried turning point...,2017-05-13 17:06:55,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,...,1,1,1,1,0,0,0,0,1,3
2,2,S6pQZQocMB1WHMjTRbt77A,XQfwVwDr-v0ZS3_CbbE5Xw,2,The place is cute and the staff was very frien...,2017-08-08 00:58:18,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,...,1,1,1,1,0,0,0,0,1,3
3,3,WqgTKVqWVHDHjnjEsBvUgg,XQfwVwDr-v0ZS3_CbbE5Xw,0,We came on a Saturday morning after waiting a ...,2017-11-19 02:20:23,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,...,1,1,1,1,0,0,0,0,1,3
4,4,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,Zaika,2481 Grant Ave,Philadelphia,PA,...,1,1,0,0,0,0,0,0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4691,6758,M1ge08vZxr3FtGbkv_0hdA,iHC-f9m5EEOIJMXCW3bmBA,0,We tried the veg lunch combo and it was very w...,2017-07-28 21:54:00,Swagruha Indian Cuisine,12338 Dorsett Rd,Maryland Heights,MO,...,1,1,1,0,0,0,0,0,1,2
4692,6760,f5L0GswmYnHZ30bNCtyEMQ,_HcAoG6Jj_XTj4-XNEbo6Q,0,Great to have a new spot in Temple Terrace. Fo...,2017-04-08 01:55:57,Fuzzy's Taco Shop,"5621 E Fowler Ave, Units 201-207",Tampa,FL,...,0,1,1,1,0,0,0,0,1,1
4693,6765,vZ4BXyD-omH9cacOD7i8pg,K4TlU26IH19tM_VvTMnpyg,5,This place is a gem and I highly recommend it....,2013-05-08 03:45:51,Rivista,4226 Magazine St,New Orleans,LA,...,0,1,0,1,0,0,0,0,0,1
4694,6766,R_w4zUc5-dPIgCreDBL5PA,PXsDX1wvizL93PcMAgxQ7w,1,Good food and decent beers. They have TVs at t...,2014-08-25 03:40:53,Nook's Pour House,2043 Rt 130 S,Florence,NJ,...,1,1,0,1,0,0,0,0,1,3
4695,6767,_b2Yvq8LZ9sdNAEjS7jgEw,yqBU6jO9e988dwxBkstJFQ,2,This location has a drive-up window... great f...,2011-02-15 14:44:31,Papa Murphy's,11815 Allisonville Road,Fishers,IN,...,0,1,1,0,0,0,0,0,0,2

In [73]:
final_df.to_csv('cleaned_dataframe.csv')